---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-python.fullname" . }}
  labels:
    {{- include "k8s-python.labels" . | nindent 4 }}
data:
  serviceconfig.yaml: |
    {{- include "k8s-python.config" . | nindent 4 }}
