---
apiVersion: "security.istio.io/v1beta1"
kind: RequestAuthentication
metadata:
  name: {{ include "k8s-python.fullname" . }}
  labels:
    {{- include "k8s-python.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-python.selectorLabels" . | nindent 6 }}
  #   peers:
  #   - mtls: {}
  jwtRules:
  {{-  tpl (toYaml .Values.devsecops.RequestAuthentication.jwtRules) . | nindent 4 }}
