---
logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    standard:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      level: INFO
      stream: ext://sys.stdout
  loggers:
    k8spython.hams:
      handlers: [console]
      level: WARNING
      propagate: False
  root:
    handlers: [console]
    level: INFO
# checks:
#   timeout: 5
#   fails: 2
#   preflights: []
#   # - http://localhost:4201
#   shutdowns: []
hams:
  url: http://0.0.0.0:8079
  prefix: hams
webservice:
  prefix: pie/v0
  url: http://0.0.0.0:8080
events:
  chunkDuration: P0DT0H0M1S
  checkTime: P0DT0H0M0.500S
  maxChunks: 100
