name: package-helmnew-chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

  workflow_dispatch:

jobs:
  package-helm-chart:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        id: set-variables
        run: |
          SHORTER_REPO=${GITHUB_REPOSITORY%:*}
          LOWER_REPO=${SHORTER_REPO@L}
          echo "REPOSITORY=$LOWER_REPO"
          echo "REPOSITORY=$LOWER_REPO" >> "$GITHUB_ENV"

        #   echo "REPOSITORY=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
        #   echo "REPOSITORY=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
        #   echo "VERSION=$(yq -r .version ./charts/sample-app/Chart.yaml)" >> "$GITHUB_OUTPUT"

      - name: Env variable output
        id: test-variables
        run: |
          cd chart
          find . -type d -maxdepth 1 -not -path "." | while read dir; do
            echo "Processing directory: $dir"
            chart_info=$(helm show chart "$dir" 2>/dev/null)

            chart_name=$(echo "$chart_info" | grep '^name:' | awk '{print $2}')
            chart_version=$(echo "$chart_info" | grep '^version:' | awk '{print $2}')
            echo "Packaging: $chart_name: $chart_version"

            helm package "$dir"

          done
        #   echo ${{ steps.set-variables.outputs.REPOSITORY }}
        #   echo ${{ steps.set-variables.outputs.VERSION }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}


    #   - name: Package and push helm chart
    #     run: |
    #       helm package ./charts/sample-app --version ${{ steps.set-variables.outputs.VERSION }}
    #       helm push ./sample-app-chart-${{ steps.set-variables.outputs.VERSION }}.tgz oci://${{ steps.set-variables.outputs.REPOSITORY }}/charts

#   publish-helm-chart:
#     permissions:
#       id-token: write
#       packages: write
#       contents: write
#       actions: read
#       deployments: read
#       pull-requests: read

#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

#       - name: Publish Helm chart to GitHub Pages
#         uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260 # v1.7.0
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           linting: off
